version: '3.8'

services:
  web:
    image: flutter_web_app:latest
    ports:
      - "9000:9000"
    volumes:
      - ./build/web:/usr/share/nginx/html:ro
    depends_on: [] # Adicione outros serviços aqui se houver
    restart: always